title: Applied Linear Algebra
author: UBC Math
exclude_patterns: ["README.md"]
logo: img/nn.png
sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
html:
  home_page_in_navbar: false
  use_repository_button: true
launch_buttons:
  jupyterhub_url: https://ubc.syzygy.ca/jupyter
repository:
  url: https://github.com/UBCMath/math307
